### ISSUE TITLE
Stylize 'PokemonFullView' component

### ISSUE THREAD

**Issue by nipeshkc7** [nipeshkc7/the-pokemon-app#1]
The component named 'PokemonFullView' is a modal that display pokemon base-stats and upgraded stats. Stylize this component to look more aesthetically pleasing.  My suggestion is add a progress bar for the stats (ranging from 0 to 350). 

![stylize](https://user-images.githubusercontent.com/22165220/83218424-4230d000-a1b1-11ea-8dcb-82a381829559.JPG)

**Comment by AbhishekJadhav2002** [comment]
> The component named 'PokemonFullView' is a modal that display pokemon base-stats and upgraded stats. Stylize this component to look more aesthetically pleasing. My suggestion is add a progress bar for the stats (ranging from 0 to 350).
> 
> ![stylize](https://user-images.githubusercontent.com/22165220/83218424-4230d000-a1b1-11ea-8dcb-82a381829559.JPG)

Hey @nipeshkc7! I can work on this task, will you please assign me ?
